Finish the rest of the docs
Boy0000/documentation pull request #1
Opened 2022-08-28 13:16 UTC by ClickNinYT

title say it, idk what to say here lol

2022-08-28 14:27 UTC, Boy0000 commented on mechanics/furniture-mechanic/farming-mechanic.md
> +      dryout: 10000
dont think this property does anything does it?

2022-08-28 14:27 UTC, Boy0000 requested changes
otherwise looks good

2022-08-29 11:58 UTC, ClickNinYT commented on mechanics/furniture-mechanic/farming-mechanic.md
> +      dryout: 10000
It's in the old example config.
from my test that `dryout` thing doesn't do anything as the Planter Box never go dry again.

2022-08-29 14:59 UTC, Boy0000 commented on mechanics/furniture-mechanic/farming-mechanic.md
> +      dryout: 10000
it means nothing because dryout isnt a property in evolution mechanic.
it can be removed afaik. dryout is only in mechanics.yml for the farmblocks i believe

2022-12-08 07:33 UTC, closed without merging